ose: add a check to if pixiewps exists
* this project has no pip requirements, but requires the system to have pixiewps installed
* add a check for it, instead of returning this confusing error:

>>>
...
File "/usr/lib64/python3.13/subprocess.py", line 1969, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pixiewps'
<<<

Signed-off-by: chickendrop89 <chickendrop89@gmail.com>