os-e: script: exit on M2D WPS message received
* The "M2D" WPS message simply means the registrar isn't ready to enroll the device yet, thus we should exit and instruct the user to try later

* This also fixes a ValueError, as this WPS message was probably unexpected to the developer who has written this code in the past:

n = int(line.split('Received M')[1])
      ^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '2D'

Signed-off-by: chickendrop89 <chickendrop89@gmail.com>